packages/core/src/components/input/input.spec.ts, packages/core/src/components/input/input.tsx, packages/core/src/components/input/stories/input.args.ts, packages/core/src/components/input/stories/input.core.stories.tsx
[Issue](https://github.com/juntossomosmais/atomium/issues/224)
- switch from shadow: true to scoped:true in order to form validity.
- update tests 
- improve docs args to set required
Input Component
Stencil currently don't suport form controller, see [issue](https://github.com/ionic-team/stencil/issues/2284).
example code:
```html
<form onsubmit="return false">
<atom-input
required="true"
type="email"
></atom-input>
<button>submit</button>
</form>
```
Before
https://github.com/juntossomosmais/atomium/assets/6757777/52389899-58d4-4c54-8e8f-9bbf255aba18
After
https://github.com/juntossomosmais/atomium/assets/6757777/22b4bcaa-8bc3-4f34-9e8b-f247d2c828ae
=> fix: input validity

packages/core/stencil.config.ts
Add use of injection imports for vite bundlers.
Build and config of modules.
Reset to the last commit and release of stable version.
Doc stencil: https://stenciljs.com/docs/config-extras#enableimportinjection
Tests in another projects 
=> chore: add extra option to apply use on vite

packages/core/src/components/button/button.spec.ts, packages/core/src/components/button/button.tsx
fix the button behavior when type is submit or reset
it only impacts the AtomButton behavior
revert the commit
**Before**
**After**
=> fix: button-form-functions

packages/core/src/components/badge/badge.scss, packages/core/src/components/badge/badge.spec.ts, packages/core/src/components/badge/badge.tsx, packages/core/src/components/badge/stories/badge.args.ts, packages/core/src/components/badge/stories/badge.core.stories.tsx, packages/core/src/components/badge/stories/badge.react.stories.tsx
[Task](https://juntossomosmais.monday.com/boards/1521247929/pulses/4928114471)
The badge component has been created, it should display in the storybook correctly.
Only in the storybook
- Reset commit to the previous version.
https://github.com/juntossomosmais/atomium/assets/59345698/61b57db0-1826-4744-8a98-dc2cef2f625d
=> feat: create badge component

packages/core/src/components/badge/badge.scss, packages/core/src/components/badge/badge.tsx
Adding propriety `line-height: 0` in `Host` of  `badge` component, because the component needs to conform to the context of the container it's embedded in.
[Component badge](https://github.com/juntossomosmais/atomium/pull/239)
Reset commit to the previous version.
Before
After
=> fix: use line-height in badge

.stylelintrc.json, package-lock.json, package.json
- Update `@juntossomosmais/linters` to 0.5.0
- Import `@juntossomosmais/linters/stylelint.config.scss.js` to `scss`
This version should have the same behavior as before
=> chore(deps): update @juntossomosmais/linters

packages/core/src/components/button/button.tsx
- Add `stop.propagation` inside `handleClick` to avoid emit event twice
Button was emitting click events twice
For now are emitting just once
=> fix(core): add stop propagation to avoid button to emit event twice

README.md
- change `storybook:build` to `docs:build`
Resolves #285
=> docs: fix wrong command

.github/workflows/ghpages.yml, .github/workflows/release-and-publish-packages.yml, apps/docs/package.json, package-lock.json, package.json, packages/core/package.json, packages/icons/README.md, packages/icons/package.json, packages/react/package.json, packages/tokens/package.json
[Task](https://juntossomosmais.monday.com/boards/3957397225/pulses/5479622950)
- Improve build for all applications using `nx`
- Change CICD to use `nx` to build
For now, we start using `dependsOn` to build applications in the right order instead of using a lot of `npm scripts` to do that. 
Fix the wrong build order in `nx.json` and `package.json` files.
=> chore: improve buildings using nx

packages/core/src/components/select/select.spec.ts, packages/core/src/components/select/select.tsx, packages/core/src/components/select/stories/select.args.ts, packages/core/src/components/select/stories/select.core.stories.tsx, packages/core/src/components/select/stories/select.react.stories.tsx
[Task](https://juntossomosmais.monday.com/boards/1521247929/pulses/5568097271)
Possibility to pass default value for Atom Select and allow to pass label in options object.
- Atom-Select
Revert to the previous stable release.
https://github.com/juntossomosmais/atomium/assets/54173994/e2512184-112c-40a8-8c0b-1aadd48e808a
=> fix(atom-select): add possibility to pass default value

packages/core/src/components/input/input.scss
[Task](https://juntossomosmais.monday.com/boards/1756815464/pulses/5277352428)
Adds a specificier class to the input border-radius styles so it can be rendered correctly on react apps. 
React projects can get the the input with correct border-radius from atomium tokens.
https://github.com/juntossomosmais/web-customer-typescript/wiki/Processo-para-reverter-Deploy
=> fix(core): add specificity to input border-radius class

packages/core/src/components/input/input.tsx, packages/core/src/components/textarea/textarea.tsx
[Task](https://juntossomosmais.monday.com/boards/1756815464/pulses/5277352428)
Added `Watch` decorator and `watchValueHandler` method for right reactivity behavior with onAtomChange prop. 
The prop onAtomChange runs on every value update while typing on react applications. 
[Describe which plan we should follow if this delivery has to be reversed.](https://login.microsoftonline.com/49158df8-04df-4db2-a1ae-ee3949ca3984/oauth2/authorize?client%5Fid=00000003%2D0000%2D0ff1%2Dce00%2D000000000000&response%5Fmode=form%5Fpost&response%5Ftype=code%20id%5Ftoken&resource=00000003%2D0000%2D0ff1%2Dce00%2D000000000000&scope=openid&nonce=AC2D47141A613BA5C1B6092D4707302171E1DA38D8662F3B%2DBDF23000C02955542D2DAF0DFBC9EC27F263CFC1C00238D3ABB4772C8CB9B8CD&redirect%5Furi=https%3A%2F%2Fvotorantimindustrial%2Es …
=> fix(core): add watch decorator for value prop

packages/core/src/components/input/input.scss
[Task](https://juntossomosmais.monday.com/boards/1756815464/pulses/5277352428)
Add more specific class to has-icon class so the input can have the same space between the icon and the type area on both fill styles.
Both fill styles will have the same space between the icon and the type area.
Before:
After:
=> fix(core): add more specific has-icon class

packages/core/src/components.d.ts, packages/core/src/components/icon/icon.spec.ts, packages/core/src/components/icon/icon.tsx, packages/core/src/components/icon/stories/icon.args.ts, packages/core/src/components/icon/stories/icon.core.stories.tsx
[Task](https://juntossomosmais.monday.com/boards/5143488854/views/113762127/pulses/6008499016)
Change size prop into icon component to set font-size style value. This component use font-size css to do this customization as recommended by [ionic icon](https://ionic.io/ionicons/usage?_gl=1*1d4s5r6*_ga*OTIwNTQxNzI1LjE2OTcwNTAwMTU.*_ga_REH9TJF6KF*MTcwNzQ4MzMwNS43LjEuMTcwNzQ4MzM0MS4wLjAuMA..)
Alternative prop to customize icon size with specific values
=> feat: add font size prop into icon component

packages/core/src/components/button/button.spec.ts, packages/core/src/components/button/button.tsx, packages/core/src/components/button/stories/button.core.stories.tsx, packages/core/src/components/button/stories/button.react.stories.tsx
[Task](https://juntossomosmais.monday.com/boards/1521247929/pulses/6204254489)
Currently, when we are using the button as a link, it is not possible to have the default behavior because we are preventing it through "onClick".
A small check was added that validates whether it is a link or not.
- Atom-Button
- Revert merge
https://github.com/juntossomosmais/atomium/assets/54173994/84eab80a-3fa1-473e-9f4b-cc7a466e397c
=> fix(button): use default behavior when is link

packages/core/src/components/alert/alert.scss
- Remove the wrong `width`
- Remove unnecessary `margin-top`
This width was flattening the icon wrongly
Before
After
=> fix(alert): remove wrong width on icon size

packages/core/src/components/button/button.scss
- Adjust button slot align to center
- Button component with an icon
| Before | After |
| ----- | ------ | 
| ![before](https://github.com/juntossomosmais/atomium/assets/20569339/46211e96-9d5e-42d9-99b9-73eb2d025f6c) | ![after](https://github.com/juntossomosmais/atomium/assets/20569339/88258ac9-d260-4a53-a289-ee34fe03e123) |
=> fix(button): adjust button slot align

packages/core/src/components/grid/grid.scss, packages/core/src/components/grid/stories/grid.args.ts, utils/scss/screens.scss
[Task](https://juntossomosmais.monday.com/boards/1521247929/views/139997903/pulses/6364196601)
Added the ability to define padding for all breakpoints, documented in Storybook. The approach is mobile-first, using var(--atom-grid-padding) for breakpoints on x-small screens and when not define a specific padding in this X breakpoint.
- Atom-Grid
Storybook
Funcionality
https://github.com/juntossomosmais/atomium/assets/54173994/aab3465f-ae4c-4749-9194-01dd4d3e1fa8
=> feat(grid): add possibility to define padding

packages/vue/src/plugin.ts
[Task](https://juntossomosmais.monday.com/boards/3957397225/pulses/6836584226)
- remove `ael` and `rel` from logic to convert events to lowercase
- in `ce` add just `atom` prefixed events to kebab case on install
This change should not impact any current functionality as it is a bug fix to avoid bad behavior when using `atom` prefixed events together with `ion` prefixed events.
closes #467
Revert the changes in the codebase
=> fix(vue): convert just atom prefixed events to kebab case on install

packages/core/src/components.d.ts, packages/core/src/components/container/container.scss, packages/core/src/components/container/container.spec.ts, packages/core/src/components/container/container.tsx, packages/core/src/components/container/stories/container.args.ts, packages/core/src/components/container/stories/container.core.stories.tsx, packages/core/src/components/container/stories/container.css, packages/core/src/components/container/stories/container.react.stories.tsx, packages/core/src/components/container/stories/container.vue.stories.tsx
closes #465
- Add new component
Container is a component that wraps content in an application using a max-width and padding to define the width of the content
=> feat(core): add container component

package-lock.json, package.json, packages/core/src/components.d.ts, packages/core/src/icons.d.ts
- downgrade `@stencil/core`to 4.17.2
We are receiving some errors about `Constructor for X was not found`, one of the reasons could be this update of the stencil version that we recently made
=> fix(core): downgrade @stencil/core to 4.17.2

packages/core/src/components.d.ts, packages/core/src/components/carousel/carousel.tsx
- Add a rule to avoid `disabled="true"` during loop
During the loop, the previous button was hiding. This PR will resolve this issue.
=> fix(core): avoid to prev button hiding during loop

packages/core/src/components/carousel/carousel.tsx, packages/core/src/components/carousel/stories/carousel.args.ts, packages/core/src/components/list-slider/list-slider.tsx, packages/core/src/components/list-slider/stories/list-slider.args.ts
- Add a dispatch event after the transition end of the carousel and list slider components.
This change will allow the user to know when the transition ends and can perform some action, for example adding a class to the element or using lazy loading together with `Intersection Observer`
=> feat(core): add dispatch event after transition end

packages/core/src/icons.d.ts, packages/icons/svg/mdi/watch-later-outline.svg, packages/icons/svg/mdi/watch-later.svg
[Task](https://juntossomosmais.monday.com/boards/1521247929/views/139997903/pulses/7094878329)
Add watch-later icon
- Outline
- Filled
- Icons
- Revert PR
=> feat(icons): add watch-later icon mdi

package-lock.json, packages/core/loader/cdn.js, packages/core/loader/index.cjs.js, packages/core/loader/index.d.ts, packages/core/loader/index.es2017.js, packages/core/loader/index.js, packages/core/src/components.d.ts, packages/core/src/components/link/link.scss, packages/core/src/components/link/link.spec.ts, packages/core/src/components/link/link.tsx, packages/core/src/components/link/stories/link.args.ts, packages/core/src/components/link/stories/link.core.stories.tsx, packages/core/src/components/link/stories/link.react.stories.tsx, packages/core/src/components/link/stories/link.vue.stories.tsx
Creating an atom-link component to be used combined with router components (such as Link, router-link and NuxtLink). Ideally, atom-link takes care of styling as router components work differently. This means we keep needing to import them when creating new anchor links. 
[Task](https://juntossomosmais.monday.com/boards/1757192123/views/36458908/pulses/7117677943)
Link component and its stories
Link components can be used on the projects. Available to test utilizing the version [2.10.0-alpha.2](https://github.com/juntossomosmais/atomium/pkgs/npm/atomium/250778260)
- Link
[link-Link.webm](https://github.com/user-attachments/assets/1851393f-40fa-48b2-bbed-1b2021d4271f)
- button …
=> feat(component): create link component

packages/core/src/components/carousel/carousel.spec.ts, packages/core/src/components/carousel/carousel.tsx
- Restart the carousel autoplay count after clicking on the navigation
- Stop autoplay during mouse enter
This add some improvements about autoplay inside `atom-carousel`
=> feat(carousel): reset autoplay when click on navigation and stop during mouse enter

.github/pull_request_template.md, .github/workflows/pr-title-check.yml
[Task](https://juntossomosmais.monday.com/boards/4069611459/pulses/6867486134)
Improved pull request and added PR title validation rule 
Pull Requests 
=> chore: improve template pr with suggestion title and add rule

packages/core/src/components/alert/alert.scss
- [improve the position of the icon on single line](https://github.com/juntossomosmais/atomium/commit/1110c7287f64dbc73d772cfb961b89ef3a1022bc)
Improve layout of the alert with an icon
One line
Multiple line
=> fix(alert): improve position of icon on single line

packages/core/src/components/carousel/carousel.tsx
- Remove redundancy for some methods
- Improve execution of autoplay
- Avoid to change `loop` after init
Avoid errors for `atom-carousel`
=> fix(carousel): improve carousel lifecycle to avoid redundancy

packages/core/src/components.d.ts, packages/core/src/components/select/select.scss, packages/core/src/components/select/select.spec.ts, packages/core/src/components/select/select.tsx, packages/core/src/components/select/stories/select.args.ts, packages/core/src/components/select/stories/select.core.stories.tsx, packages/core/src/components/select/stories/select.react.stories.tsx, packages/core/src/components/select/stories/select.vue.stories.tsx, packages/core/src/global/global.scss
- Add a background to the selected item
- Improve hover color
- Remove the prop to choose the color of select
Improve colors after selecting an option
closes #561
=> fix(select): add background to selected item and remove color's prop

README.md, packages/core/src/components.d.ts, packages/core/src/components/modal/modal.scss, packages/core/src/components/modal/modal.spec.ts, packages/core/src/components/modal/modal.tsx, packages/core/src/components/modal/stories/modal.args.ts, packages/core/src/components/modal/stories/modal.core.stories.tsx, packages/core/src/components/modal/stories/modal.react.stories.tsx, packages/core/src/components/modal/stories/modal.vue.stories.tsx, packages/core/src/global/global.scss
Fix modal scroll backdrop and expose isOpen Property to control opening of modal without trigger
The modal component and it's scroll behaviour
revert to the previous release
=> fix(modal): add class on mount and fix backdrop

packages/core/src/components/button/button.scss
[Task](https://juntossomosmais.monday.com/boards/1521247929/views/139997903/pulses/7599745622)
Add white-space property to allow text wrap.
- Button
Revert this PR.
| Before | After | 
|--------|------|
| ![Captura de tela 2024-10-09 - 13 55 54](https://github.com/user-attachments/assets/504fa1a6-15c0-48b5-82e9-a0fd5426f358) | ![Captura de tela 2024-10-09 - 13 55 26](https://github.com/user-attachments/assets/5df90aa7-7c3c-4fb3-b5ba-f4a18f6657ae) |
=> fix(button): add white space property to not overflow text

packages/core/src/components/input/input.tsx
[Task](https://juntossomosmais.monday.com/boards/1521247929/views/139997903/pulses/7587630449)
As we are removing the event listener in the "handleBlur" and "handleFocus" methods, libraries that use these events cannot function correctly after the first activation because we remove the event listener.
- Input
- Revert
With fix:
https://github.com/user-attachments/assets/58e97702-5d29-4eb2-a299-0fc6ddd0c960
Without fix, current production branch:
https://github.com/user-attachments/assets/f6b5200b-66f0-495a-9a3f-d917bf776281
=> fix(input): dont remove eventlistener on blur/focus

packages/core/src/components/container/container.scss
- Add `box-sizing: border-box`
This prevent container to not works correctly when project don't have `box-sizing: border-box` for all elements
=> fix(container): add box-sizing: border-box to fix size

packages/core/src/components/modal/modal.scss, packages/core/src/components/modal/modal.spec.ts, packages/core/src/components/modal/modal.tsx, packages/core/src/components/steps-modal/steps-modal.scss, packages/core/src/components/steps-modal/steps-modal.spec.ts, packages/core/src/components/steps-modal/steps-modal.tsx
Setting the new value for z-index on atom modal, the motivation is that ionic sets it too high and most of other UI libraries doesn't use this value (the value for it before was 20002) 
Atom modal component styling and Atom steps modal component
Re release of the previous version and revert on main branch
=> fix(modal): set new z index value for modal and steps modal

packages/core/src/global/global.scss
- Change `ion-color-danger` to `--color-contextual-error-regular`
=> fix(core): change ion-color-danger

packages/core/src/components.d.ts, packages/core/src/components/button/button.scss, packages/core/src/components/button/button.tsx, packages/core/src/components/button/stories/button.args.ts, packages/core/src/components/button/stories/button.core.stories.tsx, packages/core/src/components/button/stories/button.css, packages/core/src/components/button/stories/button.react.stories.tsx, packages/core/src/components/button/stories/button.vue.stories.tsx
- Add new prop `custom` to `color`
- Change docs
It will enable the use of custom colors to `atom-button` to use as social media, for example
=> feat(button): add custom color to color prop

package-lock.json, packages/core/src/components.d.ts, packages/core/src/components/steps-modal/steps-modal.spec.ts, packages/core/src/components/steps-modal/steps-modal.tsx, packages/core/src/components/steps-modal/stories/steps-modal.args.ts, packages/core/src/components/steps-modal/stories/steps-modal.core.stories.tsx, packages/core/src/components/steps-modal/stories/steps-modal.react.stories.tsx, packages/core/src/components/steps-modal/stories/steps-modal.vue.stories.tsx
adding new property to allow user to start the modal directly in a specific step even though it has more steps behind.
Change the use of primaryButtonText and secondaryButtonText to be an array of string for each step, like the titles.
Change the name of this properties to be more descriptive with the purpose
BREAKING CHANGE: Atom steps modal component and primaryButton and secondaryButton texts functionalities, the primaryButtonText and secondaryButtonText properties don't will exists by now on.
Re-release of the previous version and revert on main branch.
[Gravação de tela de 22-11-2024 11:21:28.webm](https://github.com/user-attachments/assets/1a91fce3-5811-4 …
=> feat(atom-steps-modal): initial step feature

packages/core/src/components/pagination/pagination.spec.tsx, packages/core/src/components/pagination/pagination.tsx
Minor fix on pagination when page count is less or equal a one, the bug in question was due to boundary pages.
- Pagination
- Revert PR
=> fix(pagination): edge case when count is equal a 1

packages/core/src/components/select/select.spec.ts, packages/core/src/components/select/select.tsx
In some cases, when a user clicks on an individual element inside an `ion-select`, the size of the ion-popover changes unexpectedly. For example, clicking on the arrow icon of the `ion-select` can cause the options overlay to become very small, leading to a poor user experience.
To prevent these extra clicks and ensure a consistent overlay size, the proposed solution is to add pointer-events: none to elements inside the ion-select that are not the label or icon.
Since ion-select is a web component, we must access its shadow DOM to apply this style.
- Users will be unable to click on individual elements inside the `ion-select` that are not the label or icon. This ensures that the popover opens with the correct size and prevents unexpected behavior, leading to a more consistent and improved …
=> fix(select): prevent clicks on non-interactive elements inside ion-select to ensure correct popover size

packages/core/src/components/carousel/carousel.spec.ts, packages/core/src/components/carousel/carousel.tsx
[Task](https://juntossomosmais.monday.com/boards/5143488854/views/113762127/pulses/8421876961)
Removing value validation to enable previus to index 0.
It fixes previus button of carousel.
https://github.com/user-attachments/assets/c472421b-c950-4810-aac3-226e60bda1d9
=> fix(carousel): enable previus click to back to index 0

packages/core/src/components.d.ts, packages/core/src/components/modal/modal.spec.ts, packages/core/src/components/modal/modal.tsx, packages/core/src/components/modal/stories/modal.args.ts, packages/core/src/components/modal/stories/modal.core.stories.tsx, packages/core/src/components/modal/stories/modal.react.stories.tsx, packages/core/src/components/modal/stories/modal.vue.stories.tsx
[Task](https://juntossomosmais.monday.com/boards/3328436962/pulses/8279352521)
- Adds a new canDismiss property to control the ability to close the modal.
- Adds a new idName property to use as a ref selector to differentiate teleported modals.
React | Vue | Core components
https://github.com/user-attachments/assets/f9d7f1b7-e00c-4f22-b501-535bb48e7abe
=> feat(modal): add can-dismiss property to control modal dismissal

packages/tokens/stories/2_Spacings.mdx, packages/tokens/stories/3_Typography.mdx, packages/tokens/stories/4_Screens.mdx, packages/tokens/stories/5_Grid.mdx, packages/tokens/stories/6_Misc.mdx, packages/tokens/stories/7_Elevation.mdx, packages/tokens/stories/components/Box.jsx, packages/tokens/stories/components/Table.jsx
[Task](https://juntossomosmais.monday.com/boards/3345740155/views/76424285/pulses/8487208067)
This pull request includes several changes to improve the readability and maintainability of the documentation by replacing static HTML tables with a reusable `Table` component and fixing some minor issues. The most important changes include updating multiple story files to use the new `Table` component and making minor formatting adjustments.
* [`packages/tokens/stories/components/Table.jsx`](diffhunk://#diff-74107f284f1bb66c2c0d8848b847eef9f340a73e5358d44f64b10a9c67763a91R1-R25): Created a new `Table` component to replace static HTML tables across the documentation. Ref: https://github.com/storybookjs/storybook/discussions/22613#discussioncomment-5975074
* …
=> fix(docs): adjust tokens table doc

packages/core/src/components.d.ts, packages/core/src/components/link/link.spec.ts, packages/core/src/components/link/link.tsx
[Task](https://juntossomosmais.monday.com/boards/3345740155/views/76424285/pulses/8550568856)
This pull request includes changes to the `AtomLink` component in the `packages/core/src/components/link` directory, focusing on enhancing the button's styling based on its size.
Styling improvements:
* [`packages/core/src/components/link/link.tsx`](diffhunk://#diff-dec6bb46efde8bc968dbbcd4cf71706fad0bb7202711d91c5f8350b0c4ad530fR46): Added a dynamic class to the button element to apply size-specific styles (`atom-link--${this.size}`).
* [`packages/core/src/components/link/link.spec.ts`](diffhunk://#diff-9cf748cf7c138423d2d7626ec9c56ea86a5bac4c5522566fd826170e9044b384L57-R57): Updated the test to reflect the new class name `atom-link--medium` added to the button element.
Before …
=> fix(atom-link): adjust prop size when type is button in atom-link

package-lock.json, packages/core/src/components.d.ts, packages/core/src/components/modal/modal.spec.ts, packages/core/src/components/modal/modal.tsx, packages/core/src/components/modal/stories/modal.args.ts, packages/core/src/components/modal/stories/modal.core.stories.tsx, packages/core/src/components/modal/stories/modal.react.stories.tsx, packages/core/src/components/modal/stories/modal.vue.stories.tsx
[Task](https://juntossomosmais.monday.com/boards/3328436962/views/97222821/pulses/8785771495)
This pull request introduces a new `metaData` prop to the `AtomModal` component, allowing for better testing by setting `data-testid` attributes on modal action buttons. Additionally, it updates storybook stories to include this new prop and adds a new story for automated testing.
* [`packages/core/src/components/modal/modal.tsx`](diffhunk://#diff-7fb4c73444f6323ac7310269fc6ccc9463cb97edd3cd3e634c88916598732ccdR14-R18): Added a new `metaData` prop to the `AtomModal` component to allow setting `data-testid` attributes on the primary, secondary, and close buttons.
=> feat(modal): add metadata prop allowing automated tests

packages/core/src/components/datetime/datetime.spec.ts, packages/core/src/components/datetime/datetime.tsx, packages/core/src/components/datetime/stories/datetime.args.ts, packages/core/src/components/datetime/stories/datetime.core.stories.tsx, packages/core/src/components/datetime/stories/datetime.react.stories.tsx, packages/core/src/components/datetime/stories/datetime.vue.stories.tsx
[Task](https://juntossomosmais.monday.com/boards/5143488854/pulses/9210434084)
This pull request enhances the `AtomDatetime` component by adding support for custom date and time target slots, improving its flexibility and customization options. The changes include updates to the component's functionality, tests, and storybook documentation.
* Updated `AtomDatetime` to support `date-target` and `time-target` slots, allowing users to customize the displayed date and time values when using the datetime button. (`packages/core/src/components/datetime/datetime.tsx`)
=> feat(datetime): add date-target and time-target slots

packages/core/package.json
[Task](https://juntossomosmais.monday.com/boards/5143488854/views/113762127/pulses/9286490020)
After add explicit exports, that will be needed after stencil upgrade, core.css is not found for imports.
=> fix(core): include core css on exports

packages/core/src/components.d.ts, packages/core/src/components/tooltip/stories/tooltip.args.ts, packages/core/src/components/tooltip/tooltip.spec.ts, packages/core/src/components/tooltip/tooltip.tsx
[Task](https://juntossomosmais.monday.com/boards/5143488854/views/113762127/pulses/9318826260)
Closes: https://github.com/juntossomosmais/atomium/issues/707
This pull request enhances the `AtomTooltip` component by adding new tooltip placement options and improving the handling of tooltip placement updates. The most important changes include extending the list of valid placements, updating the default placement behavior, and ensuring the tooltip's rendered placement dynamically reflects the Popper.js state.
* [`packages/core/src/components/tooltip/stories/tooltip.args.ts`](diffhunk://#diff-0a6210d13824b7f9eb6a6bd02a924bf5cdbcacb7cb6a7ddb73046127e251bfa2R33-R37): Added new placement options (`right-start`, `right-end`, `left-start`, `left-end`) to the `TooltipStoryArgs` configuration, …
=> fix(tooltip): use popper instance to get correct placement

package-lock.json, packages/core/src/components/meter/meter.scss
[Task](https://juntossomosmais.monday.com/boards/1757192123/pulses/9760558666)
This pull request makes a minor update to the `meter.scss` file, adjusting the color used for the success state of the meter component to improve visual consistency. 
* Changed the `background-color` for the `.is-success` class from `--color-contextual-success-light-1` to `--color-contextual-success-regular` in `meter.scss`.
=> feat(meter): use regular color on meter component
