juntossomosmais/atomium

.stylelintrc.json, package-lock.json, package.json
[Task](https://juntossomosmais.monday.com/boards/3957397225/pulses/4831035831)
Update `@juntossomosmais/linters` and extends `@juntossomosmais/linters/stylelint.config.js`
- `.stylelintrc.json` using `@juntossomosmais/linters/stylelint.config.js`
Remove extends
=> chore: extends stylelint.config.js from @juntossomosmais/linters

apps/docs/stories/architecture-decision-records/0012-why-have-a-carousel-with-swiper.stories.mdx, apps/docs/stories/architecture-decision-records/0013-why-using-virtual-carousel-item.stories.mdx, package-lock.json, package.json, packages/core/sonar-project.properties, packages/core/src/components/carousel/carousel.scss, packages/core/src/components/carousel/carousel.spec.ts, packages/core/src/components/carousel/carousel.tsx, packages/core/src/components/carousel/stories/carousel-item/carouse-item.args.ts, packages/core/src/components/carousel/stories/carousel-item/carousel-item.core.stories.tsx, packages/core/src/components/carousel/stories/carousel-item/carousel-item.react.stories.tsx, packages/core/src/components/carousel/stories/carousel-item/carousel-item.tsx, packages/core/src/components/carousel/stories/carousel/carouse.args.ts, packages/core/src/components/carousel/stories/carousel/carousel.core.stories.tsx, packages/core/src/components/carousel/stories/carousel/carousel.react.stories.tsx, packages/core/src/components/carousel/stories/carousel/style.css, packages/tokens/src/tokens.scss, packages/tokens/stories/6_Misc.stories.mdx, packages/tokens/stories/7_Elevation.stories.mdx, packages/tokens/stories/components/Box.jsx
[Task](https://juntossomosmais.monday.com/boards/3035294429/views/95907691/pulses/4758205321)
**Carousel**
- Atom Carousel component using Swiper
- Atom Carousel Item components
- ADR about Carousel, Ionic and Swiper
- ADR about te problem with swiper and the conversio of atom-component-item into swiper slide
** Side Effects **
- Elevation tokens (was used on carousel)
- Border Radius missing tokens  (was used on carousel)
- Fix doc abour transition token
- Create visual ui box component to be used on Storybook
Adding carousel to Atomium DS, in order to replace current carousel component, and remove one dependency on the vue 3 migration.
Reset commit to the previous version 02b65773dbd33eade6761dedab03eee6775d0bbe
Nuxt
https://github.com/juntossomosmais/atomium/assets/6757777/26b45690-c00e …
=> feat: carousel component

apps/docs/stories/1_4_Icons.stories.mdx, packages/core/src/components/icon/icon.spec.ts, packages/core/src/components/icon/icon.tsx
[Task](https://juntossomosmais.monday.com/boards/3957397225/views/89792005/pulses/4969107763)
- Add new icon url using cdn
- Icon component
- Change icon url to old version
=> fix(icon): use jsm cdn

.npmrc.example, README.md
Adding section how to configure ssh token
README file
=> docs(readme): adding infos how to configure ssh token

packages/core/src/components.d.ts, packages/core/src/components/carousel/carousel.spec.ts, packages/core/src/components/carousel/carousel.tsx, packages/core/src/components/carousel/stories/carousel.args.ts
[Task](https://juntossomosmais.monday.com/boards/5148603138/views/113860899/pulses/5715147945)
New prop to center carousel items
New optional prop for Carousel
Reverse to stable release
=> feat: new prop to center corousel component

packages/core/src/icons.d.ts, packages/icons/svg/mdi/compare-arrows.svg
[Task](https://juntossomosmais.monday.com/boards/1521247929/pulses/5728504578)
- Add icons for new Point Transfer menu item
- Icons
- Revert this merge
=> feat(icons): add compare arrows icon

package-lock.json, package.json
[Task](https://juntossomosmais.monday.com/boards/3957397225/views/89792005)
- closes #365 
- closes #364
- closes #363 
- closes #362
- closes #361
Update dependencies
=> chore(deps): update dependencies 

packages/core/src/components.d.ts, packages/core/src/components/carousel/carousel.spec.ts, packages/core/src/components/carousel/carousel.tsx, packages/core/src/components/carousel/stories/carousel.args.ts
[Task](https://juntossomosmais.monday.com/boards/6352064546/views/138194614/pulses/6438916239?notification=4435615211)
New prop [watchSlidesProgress](https://swiperjs.com/swiper-api#param-watchSlidesProgress)
Describe what impacts this delivery has and whether it can cause side effects in other parts of the application.
=> feat: add new watch-slides-progress carousel prop

packages/core/src/components/carousel/carousel.scss, packages/core/src/components/carousel/carousel.spec.ts, packages/core/src/components/carousel/carousel.tsx, packages/core/src/components/carousel/stories/carousel.args.ts, packages/core/src/components/carousel/stories/carousel.core.stories.tsx, packages/core/src/components/carousel/stories/carousel.react.stories.tsx, packages/core/src/components/carousel/stories/carousel.vue.stories.tsx
- Improve docs
- Improve accessibility using aria-disabled
We was using class to disable the button, but it's not a good practice, so we changed to use aria-disabled to improve accessibility
=> feat(carousel): improve accessibility using aria-disabled

.github/workflows/pr-title-check.yml
Fix in regex PR title rule
Step in GH actions that verify PR title
Rollback #532
=> chore(gh-actions): fix regex pr title rule 

packages/core/src/components/button/button.scss
[Task](https://juntossomosmais.monday.com/boards/1758703826/pulses/7179216976)
Decreasing padding value from the Button component to fit our [Design System](https://www.figma.com/design/rC8E8nEOrESRPoQQGt4kSx/Styleguide-2.0?node-id=979-688&t=JibC68Kx0AjXouZd-0)
All places that was using Atom Buttons
Revert this merge
=> fix(button): decrease horizontal padding size

packages/core/src/components/tag/tag.scss, packages/core/src/components/tag/tag.spec.ts, packages/core/src/components/tag/tag.tsx
[Task](https://juntossomosmais.monday.com/boards/5143488854/views/113762127/pulses/7037239326)
- Fix the color of the type light
- Fix height tag calculation and add `tag` part to custom css.
Light fix on the size of the tag (less than 1px)
Before
After
=> fix(tag): light tag color

packages/core/src/components.d.ts, packages/core/src/components/icon/icon.scss, packages/core/src/components/icon/icon.tsx, packages/core/src/components/icon/stories/icon.args.ts
[Task](https://juntossomosmais.monday.com/boards/3957397225/pulses/7315203401?userId=20950543)
Option white for icons
You can use icon white in colorful backgrounds
=> feat(icon): add white color

packages/core/src/components/select/select.tsx, packages/core/src/components/select/stories/select.core.stories.tsx, packages/core/src/components/select/stories/select.react.stories.tsx, packages/core/src/components/select/stories/select.vue.stories.tsx
- Add async to method to add tag to select 
- Fix docs to open select with tags
=> fix(select): add async to method to avoid promise warning

package-lock.json, packages/core/src/components.d.ts, packages/core/src/components/modal/modal.spec.ts, packages/core/src/components/modal/modal.tsx, packages/core/src/components/modal/stories/modal.args.ts, packages/core/src/components/modal/stories/modal.core.stories.tsx, packages/core/src/components/modal/stories/modal.react.stories.tsx, packages/core/src/components/modal/stories/modal.vue.stories.tsx, packages/core/src/components/steps-modal/steps-modal.spec.ts, packages/core/src/components/steps-modal/steps-modal.tsx, packages/core/src/components/steps-modal/stories/steps-modal.args.ts, packages/core/src/components/steps-modal/stories/steps-modal.core.stories.tsx, packages/core/src/components/steps-modal/stories/steps-modal.react.stories.tsx, packages/core/src/components/steps-modal/stories/steps-modal.vue.stories.tsx
- Change `disablePrimary` to `disablePrimaryButton`
- Change `disableSecondary` to `disableSecondaryButton`
- Change `primaryText` to `primaryButtonText`
- Change `secondaryText` to `secondaryButtonText`
Change the props name, it will affect components that are using inside projects
=> feat(modal): change buttons props to be more declarative

packages/core/src/icons.d.ts, packages/icons/svg/custom/discount-tag.svg
[Task](https://juntossomosmais.monday.com/boards/5143488854/views/113762127/pulses/7876841121)
New custom icon, discount-tag.
Describe what impacts this delivery has and whether it can cause side effects in other parts of the application.
=> feat(icons): add new discount-tag icon

packages/core/src/components/steps-modal/steps-modal.spec.ts, packages/core/src/components/steps-modal/steps-modal.tsx
[Task](https://juntossomosmais.monday.com/boards/1757192123/pulses/7463658557)
Fix the use of wrong names to atom-modal disable button props.
steps modal
Re-release to the previous version and revert of main branch
=> fix(steps-modal): use correct prop name to disable primary and secondary button

packages/core/src/components.d.ts, packages/core/src/components/pagination/pagination.scss, packages/core/src/components/pagination/pagination.spec.tsx, packages/core/src/components/pagination/pagination.tsx, packages/core/src/components/pagination/stories/pagination.args.ts, packages/core/src/components/pagination/stories/pagination.core.stories.tsx, packages/core/src/components/pagination/stories/pagination.react.stories.tsx, packages/core/src/components/pagination/stories/pagination.vue.stories.tsx
This pull request introduces a new pagination component to the project. The changes include the addition of the component's styling, functionality, tests, and storybook stories for different frameworks (React, Vue, and Web Components). Here are the most important changes:
* [`packages/core/src/components/pagination/pagination.tsx`](diffhunk://#diff-14070b827e22730dbdedb44e9abd426f155129cd7cdd68096dc16b67ed83843bR1-R168): Added the `AtomPagination` component with properties `page` and `count`, event handling for page changes, and rendering logic for pagination items.
* [`packages/core/src/components/pagination/pagination.scss`](diffhunk://#diff-34ef19b582675cf6b77cc716a336c134333651c06c564356acf9c3071c636982R1-R50): Added the SCSS styles for the `AtomPagination` component, including styles …
=> feat(pagination): create pagination component

README.md
[Task](https://juntossomosmais.monday.com/boards/3328436962/pulses/8465732828)
- adds correct url to vue documentation
- adds correct script to build
Describe what impacts this delivery has and whether it can cause side effects in other parts of the application.
=> fix(docs): update readme documentation

package-lock.json, package.json, packages/core/src/components.d.ts, packages/core/src/components/modal/stories/modal.args.ts, packages/core/src/components/steps-modal/steps-modal.spec.ts, packages/core/src/components/steps-modal/steps-modal.tsx, packages/core/src/components/steps-modal/stories/steps-modal.args.ts, packages/core/src/components/steps-modal/stories/steps-modal.core.stories.tsx, packages/core/src/components/steps-modal/stories/steps-modal.react.stories.tsx, packages/core/src/components/steps-modal/stories/steps-modal.vue.stories.tsx
[Task](https://juntossomosmais.monday.com/boards/3328436962/pulses/8279332371?filter=XQAAAAKwAAAAAAAAAABBqQqHk62Wwa8yt9cbbXI48HpL2ei1XixEiNVOhiWmf4IrTn4lrcVxz0d8EzlqDpxL1dc7i9JjI1nNW0HEFgqaXhsDsHWTHjMEE6-qlUKWgWTaunFWUdBXUcOor4nRBu0Fw_waOgg07m9BEERYVyGdCL2MilBe8_Dj_2b5UeGvHpmkbgzzbp9D2VaQa9kTJfavyU3TtP7vDsA)
This pull request introduces several changes to the `steps-modal` component and its associated files to support the addition of meta-data properties and improve the flexibility of the component. The most important changes include adding the `metaData` property to the `steps-modal` component, updating stories to include the new property, and adding corresponding tests.
Other changes:
* [`package.json`](diffhunk://#diff-7ae45ad102eab3b6d7e7896acd08c427a9b25b346470d7bc6507b6481575d519L116 …
=> feat: add meta data on steps modal

.github/workflows/preview.yml, packages/core/src/components/tooltip/stories/tooltip.args.ts, packages/core/src/components/tooltip/tooltip.scss
[Task](https://juntossomosmais.monday.com/boards/5143488854/views/113762127/pulses/8976808169)
This pull request introduces a new customizable CSS variable for the tooltip component, allowing developers to specify a custom background color. The changes include updates to the component's arguments and its styling to support this feature.
=> feat(tooltip): custom bg variable

package-lock.json, packages/core/src/components.d.ts, packages/core/src/components/list-slider/list-slider.spec.ts, packages/core/src/components/list-slider/list-slider.tsx, packages/core/src/components/list-slider/stories/list-slider.args.ts, packages/core/src/components/list-slider/stories/list-slider.core.stories.tsx
[Task](https://juntossomosmais.monday.com/boards/3328436962/views/97222821/pulses/8527506120)
This pull request adds a new `step` property to the `AtomListSlider` component, allowing users to control the number of items to advance or go back when navigating. It also updates the corresponding stories to demonstrate this new functionality. Below are the key changes:
* Added a new `step` property to the `AtomListSlider` component, with a default value of `1`. This property determines the number of items to navigate forward or backward. (`packages/core/src/components/list-slider/list-slider.tsx`, [packages/core/src/components/list-slider/list-slider.tsxR22](diffhunk://#diff-2c5a766e4d119ac62f36714f2fa93937fa676a54df335a9b39c4022a3de81b29R22))
* Updated navigation logic to use the `step` value …
=> feat(atom-list-slider): add 'step' property to the interface

package-lock.json, package.json, packages/core/loader/package.json, packages/core/package.json
[Task](https://juntossomosmais.monday.com/boards/5143488854/views/113762127/pulses/9270652947)
This pull request downgrade the stencil version to lead with CJS build error.
Stencil issue: https://github.com/stenciljs/core/issues/6270
=> fix(deps): downgrade stencil version

packages/core/src/components/datetime/datetime.spec.ts, packages/core/src/components/datetime/datetime.tsx, packages/core/src/components/datetime/stories/datetime.react.stories.tsx
This pull request enhances the `AtomDatetime` component by improving its handling of various input values, refining its internal logic, and updating tests to ensure robustness. The key changes include better handling of empty or invalid input values, improvements to date sorting and formatting, and updates to ensure proper behavior of min/max and multiple/range mode properties.
* Introduced helper methods (`filterEmptyStrings`, `handleStringValue`, and `handleCustomEventValue`) to cleanly process empty strings, arrays, and custom event values. This ensures that invalid or empty inputs are gracefully handled. (`packages/core/src/components/datetime/datetime.tsx`, [packages/core/src/components/datetime/datetime.tsxR99-R139](diffhunk://#diff-283df32286ec2fd9e77ab2f8dd00915e18be2089f494c7c80b2 …
=> fix(datetime): improve value normalization and prevent ionic parsing warnings
